### ISSUE TITLE
PyPI sdist missing requirements.txt

### ISSUE THREAD

**Issue by jayvdb** [aiokitchen/aiomisc-dependency#9]
```py
Traceback (most recent call last):
  File "setup.py", line 55, in <module>
    install_requires=load_requirements('requirements.txt'),
  File "setup.py", line 28, in load_requirements
    with open(fname) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by dizballanze** [comment]
Should be fixed [here](https://pypi.org/project/aiomisc-dependency/0.1.17/)
